name: 'BeValued Label Checker'
description: 'Check for a label on a Pull Request. Default is "Passed QA Testing"'
branding:
  color: green
  icon: smile
inputs:
  label-name:  # id of input
    description: 'The label required. If this is not present, the check will fail. If it is present, it will pass'
    required: true
    default: 'Passed QA Testing'
runs:
  using: 'node16'
  main: 'dist/index.js'